// App actions
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const SET_INIT_TO_DEFAULT = 'SET_INIT_TO_DEFAULT';
export const APP_INIT = 'APP_INIT';
export const GET_MY_IP_INFO = 'GET_MY_IP_INFO';
export const EVENT_TAB_CHANGED = 'EVENT_TAB_CHANGED';
export const LOADING_SCREEN = 'LOADING_SCREEN';
export const NOTIFICATIONS_COUNT = 'NOTIFICATIONS_COUNT';
export const NOTIFICATION_TOKEN = 'NOTIFICATION_TOKEN';
export const NOTIFICATIONS_RECEIVED = 'NOTIFICATIONS_RECEIVED';
export const NOTIFICATION_COUNT_DECREASE = 'NOTIFICATION_COUNT_DECREASE';
export const NOTIFICATION_COUNT_INCREASE = 'NOTIFICATION_COUNT_INCREASE';
export const OPEN_BOTTOM_POPUP = 'OPEN_BOTTOM_POPUP';
export const CLOSE_BOTTOM_POPUP = 'CLOSE_BOTTOM_POPUP';
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const ADD_NEW_POPUP = 'ADD_NEW_POPUP';
export const APP_INIT_LANGUAGES = 'APP_INIT_LANGUAGES';
export const PERSIST_REHYDRATE = 'persist/REHYDRATE';
export const SHOW_TOAST = 'SHOW_TOAST';
export const HIDE_TOAST = 'HIDE_TOAST';
export const SET_PROFILE_TAB = 'SET_PROFILE_TAB';
export const SET_FCM_DEVICE_TOKEN = 'NOTIFICATION_TOKEN';
export const SET_USER_TOKEN = 'SET_USER_TOKEN';
export const SET_USER_LOGGED_IN = 'SET_USER_LOGGED_IN';

//Navigation types
export const RESET_TO_HOME = 'RESET_TO_HOME';
export const RESET_TO_ONBOARDING = 'RESET_TO_ONBOARDING';
export const NAVIGATION_BACK = 'Navigation/BACK';
export const NAVIGATION_NAVIGATE = 'Navigation/NAVIGATE';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const ON_TAB_CHANGE = 'ON_TAB_CHANGE';
export const RESET_TAB = 'RESET_TAB';
export const NAVIGATION_MAIN = 'NAVIGATION_MAIN';

//User types
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_PROFILE_IMAGE = 'UPDATE_PROFILE_IMAGE';
export const DELETE_PROFILE_IMAGE = 'DELETE_PROFILE_IMAGE';
export const SET_PASSWORD = 'SET_PASSWORD';